# Generated by Django 5.0.1 on 2025-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatedimage',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
