services:
  - type: web
    name: face-detection-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y cmake
      pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
